version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: $PORT # Change to your real port
        DATABASE_URL: $DATABASE_URL # Your DB URL here
    environment:
      PORT: $PORT # Should match build args
      DATABASE_URL: $DATABASE_URL # Your DB URL here
    ports:
      - "$PORT:$PORT" # host:container
    restart: always
    command: ["npm", "run", "start"]